version: '2'

services:
  web:
    build: web
    ports: ["80:80"]
    volumes: ["./web/static:/usr/share/nginx/html"]
    restart: always

  book-api:
    build: book-api
    ports: ["3005:3005"]
    links: [mongo]

  mongo:
    image: mongo:3.3.8
    ports: ["27017:27017"]
